### ISSUE TITLE
:en is not a valid locale

### ISSUE THREAD

**Issue by AlexVPopov** [tkadauke/i18n_tools#5]
When I run `LOCALE=en rake translations:unused` for an app running Ruby 2.1.1 and Rails 4 I get:

``` bash
rake aborted!
:en is not a valid locale
```

Any help is appreciated. Thank you.

**Comment by tkadauke** [comment]
Hmm, I can't reproduce that with a new test app with Ruby 2.1.1 and Rails 4.1.0. Are you sure "en" is really a defined locale?

**Comment by AlexVPopov** [comment]
Yes, I am sure. The app I am trying to use it on is a rather complicated with a lot of configurations, so I think it would be relatively hard to debug, I am closing the issue for now.
